Fix #28 refactored remote Llama
NM-TAFE/dip-programming-prj-advanced-gui-awesome pull request #29
Opened 2024-06-07 12:44 UTC by Claire863

Refactoring :
 - File name (remote_llama.py instead of remotellama.py
 - Class name (Llama instead of LlamaInterface)
 - Class methods (static methods instead of standard methods)
 - Document on url = "http://chaostree.xyz:3002/" in Class Llama

2024-06-07 13:42 UTC, Claire863 commented
Added Cameron as reviewer as he has been working on the LLama Class (or LLamaInterface)

2024-06-07 14:14 UTC, bhandareasmita approved these changes
I have reviewed the changes and everything looks good for me.

2024-06-07 14:48 UTC, rafrafavi commented on app/remote_llama.py
> +    url = "http://chaostree.xyz:3002/"  # URL that points to llama instance running on local server
Documentation should be in the form of class docstring - the comment does not appear to be accurate since chaostree is not running on a local server, rather it is someone else's computer at least with respect to me - what steps or prerequisites does it relate to? how was it trained and set up? Has this been documented?

2024-06-08 15:21 UTC, Claire863 commented on app/remote_llama.py
> +    url = "http://chaostree.xyz:3002/"  # URL that points to llama instance running on local server
Documentation updated.

Detailed explanation on server/API
Detailed explanation on which/how Llama is used

2024-06-08 15:29 UTC, 20095325 requested changes

2024-06-08 15:29 UTC, 20095325 commented on app/remote_llama.py
> +    Via API, Ollama receives a prompt, runs LLM models, and send the response back.
What is Ollama? should this not just say Llama?

2024-06-09 12:06 UTC, Claire863 commented
Agreed we shouldn't mention Ollama.

It was good for me to understand how we 'accessed' Llama models, but it doesn't add anything to the core of the project and its maintainability.

Docstrings are updated.

2024-06-10 03:31 UTC, rafrafavi reviewed
My review is just focused on idiomatic python and use of requests - and still unsure about some of the functionality from a user point of view.

2024-06-10 03:31 UTC, rafrafavi commented on app/remote_llama.py
> +    url = "http://chaostree.xyz:3002/"  # url of the API running Llama
Maybe it is just me, speaking as an outsider to the project, but I still have no idea what `chaostree.xyz` is? Is it something I set up? Is it a web service you are all using? If it is something I set up are there steps to this set up?

2024-06-10 03:31 UTC, rafrafavi commented on app/remote_llama.py
> +        response = requests.post(Llama.url + 'llamapreprompt', headers=Llama.headers, json=data)
I am pretty sure the headers you manually inserted aren't needed since `json=` automatically sets the HTTP headers to application/json

2024-06-10 13:23 UTC, Claire863 commented on app/remote_llama.py
> +    url = "http://chaostree.xyz:3002/"  # url of the API running Llama
Hi Raf,
chaostree.xyz is Jarrah's server, where is installed Ollama.
The url calls to the api, the api runs Ollama (e.g. software that has Llama models embedded) and returns the result.

Nothing to step up on a user or developer perspective.

The team choose this approach because
A: Ollama uses a lot of storage (the small version - 7B - already is 50GB)
B: LLMs require a lot of GPU power and VRAM (more than the average user has free to use)

2024-06-10 15:01 UTC, Claire863 commented on app/remote_llama.py
>              elif response.status_code == 500:
Check on requests documentation, they also state that best practice is to use raise_for_status()
I would add it straight after the response (no need to wait later in code code to check).

My question is how can I test this code? How can I generate an error to see how the code responds?

![Screenshot 2024-06-10 225959](https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-awesome/assets/170336770/2784ac1b-07e5-4e95-9b4f-7b69d7b97df5)

2024-06-12 13:07 UTC, Claire863 commented on app/remote_llama.py
> +        response = requests.post(Llama.url + 'llamapreprompt', headers=Llama.headers, json=data)
Updated with the latest commit

2024-06-12 13:08 UTC, Claire863 commented on app/remote_llama.py
>              elif response.status_code == 500:
updated with the latest commit

2024-06-13 17:39 UTC, 20095325 approved these changes

2024-06-13 17:39 UTC, merged